### ISSUE TITLE
TypeError: sodium.crypto_pwhash is not a function

### ISSUE THREAD

**Issue by nanosonde** [ihrigb/node-doorbird#74]
Hi!
In the doorbird plugin for scrypted which I am currently developing, I get the following error.
The doorbird module is set as normal dependency in the plugin.
It seems that there is more that is missing.

Any idea?

```
unhandledRejection TypeError: sodium.crypto_pwhash is not a function
    at DoorbirdUdpSocket.<anonymous> (/node_modules/doorbird/dist/index.js:121:1)
    at step (/node_modules/doorbird/dist/index.js:56:1)
    at Object.next (/node_modules/doorbird/dist/index.js:37:46)
    at fulfilled (/node_modules/doorbird/dist/index.js:28:43)
unhandledRejection TypeError: sodium.crypto_pwhash is not a function
    at DoorbirdUdpSocket.<anonymous> (/node_modules/doorbird/dist/index.js:121:1)
    at step (/node_modules/doorbird/dist/index.js:56:1)
    at Object.next (/node_modules/doorbird/dist/index.js:37:46)
    at fulfilled (/node_modules/doorbird/dist/index.js:28:43)
```

**Comment by nanosonde** [comment]
Ok. Found this: https://stackoverflow.com/questions/65194012/trying-to-use-libsodium-with-web-worker-error-typeerror-sodium-crypto-pwhash-is

**Comment by nanosonde** [comment]
It seems that `libsodium-wrappers-sumo` os required instead of `libsodium-wrappers.`

**Comment by nanosonde** [comment]
With this patch, the plugin is receiving events successfully:

```diff
diff --git a/package.json b/package.json
index 44ae0c2..161f250 100644
--- a/package.json
+++ b/package.json
@@ -28,7 +28,7 @@
   "homepage": "https://github.com/ihrigb/node-doorbird#readme",
   "devDependencies": {
     "@types/jest": "^27.0.3",
-    "@types/libsodium-wrappers": "^0.7.9",
+    "@types/libsodium-wrappers-sumo": "^0.7.5",
     "@typescript-eslint/eslint-plugin": "^5.46.1",
     "@typescript-eslint/parser": "^5.47.0",
     "eslint": "^8.29.0",
@@ -41,6 +41,6 @@
   "dependencies": {
     "axios": "^1.2.1",
     "chacha-js": "^2.1.1",
-    "libsodium-wrappers": "^0.7.10"
+    "libsodium-wrappers-sumo": "^0.7.11"
   }
 }
diff --git a/src/index.ts b/src/index.ts
index a375a57..6e96fc4 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -1,4 +1,4 @@
-import libsodium from "libsodium-wrappers";
+import libsodium from "libsodium-wrappers-sumo";
 import * as chacha from "chacha-js";
 import * as dgram from "dgram";
 import * as https from "https";
```

**Comment by nanosonde** [comment]
Ok. I understood the real root cause.

In your package.json you specified `libsodium-wrappers` with version `^0.7.10`.
This would automatically install the latest patch version `0.7.11`.

However, the libsodium.js guys introduced a breaking change from `0.7.10` to `0.7.11`:
https://github.com/jedisct1/libsodium.js/issues/312

IMHO, really ugly to change just the semver patch level and introduce a breaking change.

I suggest to apply the above patch to follow their recommendation starting from `0.7.11?`.
Otherwise, specify the old version `0.7.10` as an exact version without the `^` in front.

**Comment by ihrigb** [comment]
Thanks for investigating this. I agree that this change in a patch version is awkward. I will release a patch for this.

**Comment by ihrigb** [comment]
I released a version that contains the fix: https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/releases/tag/v1.2.3
